import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../comps/Navbar'
import React from 'react';
import 'bootstrap/dist/css/bootstrap.css';
import Carousel from 'react-bootstrap/Carousel';
import styles from '../styles/Home.module.css'
import { useState } from "react";
import { useHistory } from "react-router-dom";

export default function Home() {


  return (
    <div >
      <Head>
        <title>Seoul Sahara</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Navbar/>
      <section id="home">
        <div className="container-fluid bg-pink">
          <div className="row">
            <div className="col-12 mb-5">
              <div className="d-flex justify-content-center">
                <Image src="/ss-main.png" width={500} height={400}/>  
              </div>
              <h1 className="text-center red-text">Only the best <span className="text-blue">Korean</span>  Streetfood</h1>
              
            </div>
            
          </div>
        </div>
      </section>

      <section id="about" className="history">
        <div className="container-fluid pt-5">
          <div className="row">
            <div className="col-xl-2 "></div>
            <div className="col-xl-4 ps-3 pe-3">
              <h4 className="color-gold mt-80">THE SEOUL SAHARA</h4>
              <p className="color-white">{"Diver by our passion and desire to cater only the best quality and authentic taste of homemade Japanese Maki that every Filipino deserves to experience at a very friendly price, the Juan'ts Maki food stand is created and hit the market since the begininning of the year 2021."}                
              </p>
              <p className="color-white"> 
              We aim to provide indisriminately the good food and excellent service readily for everyone to enjoy.
              </p>
            </div>
            <div className="col-xl-6 history-img">          
              {/* <img align="right" src="/history-img.jpg" alt="P" />    */}
              <div className="d-flex align-items-end justify-content-lg-end justify-content-center mt-80 mb-5 me-0 ">
                 <Image src="/ss-opening.png" width={400} height={500} alt="Picture of the author" />   
              </div>
                    
            </div>            
          </div>
        </div>
      </section>

      <section id="menu">
        <div className="container mb-5">
          <div className="row">
            <div className="col-12">
               <h3 className="text-center color-blue mt-80 ">Our menu</h3>
               <h2 className="text-center color-light-pink mt-negative mb-5 ">Satisfy your Cravings</h2>
            </div>
          </div>

          <div className="container ">
        <div className="row ">
          <div className="col-xl-4 pb-5">
            <div className="height-350">
            <div style={{ display: 'block', width: 350, padding: 30 }}>
              <h4 className="text-center red-text">Dakgangjeong</h4>
                  <Carousel>
                      <Carousel.Item interval={2000}>
                        <img
                          className="d-block w-100"
                          src="/d-chk-dynamite.png"
                          alt="Image One"
                        />
                      </Carousel.Item>
                      <Carousel.Item interval={2000}>
                        <img
                        className="d-block w-100"
                        src="/d-chk-garlic-mayo.png"
                        alt="Image Two"
                        />
                      </Carousel.Item>
                      <Carousel.Item interval={2000}>
                        <img
                        className="d-block w-100"
                        src="/d-chk-tepanyaki.png"
                        alt="Image Two"
                        />
                      </Carousel.Item>
                      <Carousel.Item interval={2000}>
                        <img
                        className="d-block w-100"
                        src="/d-chk-honey-lemon.png"
                        alt="Image Two"
                        />
                      </Carousel.Item>
                      <Carousel.Item interval={2000}>
                        <img
                        className="d-block w-100"
                        src="/d-chk-sweet-chili.png"
                        alt="Image Two"
                        />
                      </Carousel.Item>
                  </Carousel>
              </div>
              {/* carousel chicken */}
            </div>
            
          </div>

          <div className="col-xl-4 pb-5">

          <div className="height-350">
          <div style={{ display: 'block', width: 350, padding: 30 }}>
              <h4 className="text-center red-text">Corndog</h4>
                  <Carousel>
                      <Carousel.Item interval={2000}>
                        <img
                          className="d-block w-100"
                          src="/c-cali-cornia.png"
                          alt="Image One"
                        />
                      </Carousel.Item>
                      <Carousel.Item interval={2000}>
                        <img
                        className="d-block w-100"
                        src="/c-cheesy-bomb.png"
                        alt="Image Two"
                        />
                      </Carousel.Item>
                      <Carousel.Item interval={2000}>
                        <img
                        className="d-block w-100"
                        src="/c-chili.png"
                        alt="Image Two"
                        />
                      </Carousel.Item>
                      <Carousel.Item interval={2000}>
                        <img
                        className="d-block w-100"
                        src="/c-cornstar.png"
                        alt="Image Two"
                        />
                      </Carousel.Item>
                      <Carousel.Item interval={2000}>
                        <img
                        className="d-block w-100"
                        src="/c-original.png"
                        alt="Image Two"
                        />
                      </Carousel.Item>
                  </Carousel>
              </div>
              {/* carousel corndog */}
          </div>
          
          </div>

          <div className="col-xl-4">
            <div className=" height-350">
            <div style={{ display: 'block', width: 350, padding: 30 }}>
              <h4 className="text-center red-text">Tempura</h4>
                  <Carousel>
                      <Carousel.Item interval={2000}>
                        <img
                          className="d-block w-100"
                          src="/t-allstar.png"
                          alt="Image One"
                        />
                      </Carousel.Item>
                      <Carousel.Item interval={2000}>
                        <img
                        className="d-block w-100"
                        src="/t-original.png"
                        alt="Image Two"
                        />
                      </Carousel.Item>
                  </Carousel>
              </div>
              {/* carousel tempura */}
            </div>
          
          </div>
        </div>
      </div>

           </div>

   
          
      </section>

      <section id="franchise">
        <div className="container-fluid bg-violet">
           <div className="row">
              <div className="col-12 ">
                <h3 className="text-center color-gold mt-80 ">Our Franchise</h3>
                <h2 className="text-center text-light-violet mt-negative ">Made with Passion</h2>
              </div>
            </div>

            <div className="row">
            
              <div className="col-xl-7 bg-blue mt-80">
                <div className="franchise-details">
                <h4 className="color-gold mt-80">STARTER BUSINESS PACKAGE</h4>
                <p className="color-white">
We always continue to strive and delight people with all the best that we can give, through products we make with integrity and goodwill.</p>
                </div>
                
              </div>
              
              <div className="col-xl-5">
                <div className="franchise-img mt-80 ">                  
                  <Image src="/franchise-img.png" width={500} height={500} />
                </div>
                
              </div>
            </div>
        </div>
      </section>

      <section id="contact">
      <div className="row">
          <div className="col-12">
            <h2 className="text-center mt-5">Contact Us</h2>
          </div>
        
        </div>

        <form className="franchise-from">
          <div className="container mt-80 mb-80">
              <div className="row">
                  <div className="col-12">
                    <label>Name:</label>
                    <input type="text" required></input>
                  </div>
                
              </div>
            
            <div className="row">
                <div className="col-xl-6">
                    <label>Enter your Email:</label>
                    <input type="text" required></input>
                </div>
                <div className="col-xl-6">
                    <label>Enter your Phone number:</label>
                    <input type="text" required ></input>
                </div>
            </div>

            <div className="row">
                <div className="col-12">
                <label>Input your Message:</label>
                    <textarea required></textarea>
                </div>
            </div>
            
            
            
            <button className="form-button mt-3">Submit</button>
          </div>
        
      </form>
        
      </section>

      <footer className="bg-pink">
            <div className="container">
               <div className="row">
                  
                  <div className="col-xl-4"></div>
                  <div className="col-xl-4 align-items-center">
                  <Image src="/ss-main.png" width={400} height={340} alt="Picture of the author" />
                  </div>
                  <div className="col-xl-4"></div>
               </div>
            </div>
           <p className="pb-80 footer-copyright">Copyright 2021 Seoul Sahara</p> 
        </footer>
    </div>
  )
}
